# Generated by Django 6.0 on 2025-12-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfomodel',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
    ]
